version: "3.9"

services:
  spark-master:
    image: apache/spark:3.4.4
    container_name: spark-master
    hostname: spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ../workspace:/opt/workspace

  spark-worker-1:
    image: apache/spark:3.4.4
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      --webui-port 8081
      spark://spark-master:7077
    ports:
      - "8081:8081"
    volumes:
      - ../workspace:/opt/workspace

  spark-worker-2:
    image: apache/spark:3.4.4
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      --webui-port 8081
      spark://spark-master:7077
    ports:
      - "8082:8081"
    volumes:
      - ../workspace:/opt/workspace

  jupyterlab:
    image: apache/spark:3.4.4
    container_name: jupyterlab
    hostname: jupyterlab
    user: "0:0"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - PYTHONUNBUFFERED=1
      - PIP_DISABLE_PIP_VERSION_CHECK=1
    ports:
      - "8889:8888"
      - "4040:4040"
      - "4041:4041"
    volumes:
      - ../notebooks:/opt/notebooks
      - ../workspace:/opt/workspace
      - ./requirements.txt:/opt/requirements.txt:ro
      - pip-cache:/root/.cache/pip
    command: >
      bash -lc "set -e;
      mkdir -p /opt/notebooks /opt/workspace;
      echo 'Python:'; python3 --version;
      echo 'Pip:'; python3 -m pip --version;
      python3 -m pip install --no-cache-dir jupyterlab;
      python3 -m pip install --no-cache-dir -r /opt/requirements.txt;
      python3 -m jupyterlab --ip=0.0.0.0 --port=8888 --no-browser --ServerApp.token='' --ServerApp.password='' --ServerApp.allow_root=true --notebook-dir=/opt/notebooks
      "

volumes:
  pip-cache:
